# Generated by Django 4.0.3 on 2022-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True)),
                ('name_book', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
